### ISSUE TITLE
Issues in deploying the server

### ISSUE THREAD

**Issue by saravanabalagi** [slack-ruby/slack-bot-on-rails#4]
Deploy to Heroku button is awesome. There's an issue: I guess Heroku thinks it's a JS application and tries finding app.json and fails.

**Comment by zekedran** [comment]
Just do https://heroku.com/deploy?template=https://github.com/slack-ruby/slack-bot-on-rails
It's just that it was pointing to the old repo which it was perhaps forked from

**Comment by dblock** [comment]
Would you mind PRing a fix to the button in README? Thanks.

**Comment by zekedran** [comment]
"Locally" as in a dev build in my laptop (as opposed to production build on Heroku).

**Comment by zekedran** [comment]
When deploying, first I get gem installation errors
```
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

But then redeploy the same app after updating 
- spring
- gemlock file

`bundle` operations complete successfully.

But `raketasks` fail. Just click deploy button from [here](https://github.com/zekedran/slack-bot-on-rails) and paste some API_TOKEN to see the full error.

```
-----> Detecting rake tasks
 !
 !     Argument list too long -  logger -p user.notice -t "slugc[$$]" "buildpack-ruby compile id=b705690b2ac framework=rails42 status=error finish=1531322147.48 elapsed=33.49 message=Argument\ list\ too\ long\ -\ \ logger\ -p\ user.notice\ -t\ \"slugc\[\$\$\]\"\ \"buildpack-ruby\ assets_precompile\ id\=b705690b2ac\ framework\=rails42\ status\=error\ finish\=1531322147.37\ elapsed\=1.08\ message\=Could\\\ not\\\ detect\\\ rake\\\ tasks\''
 !     '\'ensure\\\ you\\\ can\\\ run\\\ \\\`\\\$\\\ bundle\\\ exec\\\ rake\\\ -P\\\`\\\ against\\\ your\\\ app\''
 !     '\'and\\\ using\\\ the\\\ production\\\ group\\\ of\\\ your\\\ Gemfile.\''
 !     '\'/tmp/build_181b8208bbf549a083a3fa423a7fce0d/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:121:\\\ warning:\\\ constant\\\ ::Fixnum\\\ is\\\ deprecated\''
 !     '\'/tmp/build_181b8208bbf549a083a3fa423a7fce0d/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:121:\\\ warning:\\\ constant\\\ ::Bignum\\\ is\\\ deprecated\''
 !     '\'rake\\\ aborted\\\!\''
 !     '\'SystemStackError:\\\ stack\\\ level\\\ too\\\ deep\''
 !     '\'/tmp/build_181b8208bbf549a083a3fa423a7fce0d/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:124:in\\\ \\\`block\\\ \\\(2\\\ levels\\\)\\\ in\\\ \\\<class:Numeric\\\>\\\'\''
.
.
.
.
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/bin/support/ruby_compile:15:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by dblock** [comment]
If you want to work through this I am happy to help.

* Locally everything should be working, so I would start there. Probably needs a `bundle update` to get all the more recent/compatible gems with whatever OS craziness is going on. That should upgrade `json` and probably fix that problem.
* Rake tasks aren't necessary for heroku edeployment, but it shouldn't end up in this `Stack Level too Deep ` error either.  I would start by introducing a newer version of Rake into Gemfile.

**Comment by zekedran** [comment]
How do I fix the SSL Error?

I had to add to Gemfile

```
gem 'faye-websocket' # or
# gem 'celluloid-io'
```

But I get the SSL Error

```
I, [2018-07-12T10:30:40.395714 #25340]  INFO -- request: POST https://slack.com/api/rtm.start
D, [2018-07-12T10:30:40.396712 #25340] DEBUG -- request: Accept: "application/json; charset=utf-8"
User-Agent: "Slack Ruby Client/0.11.1"
Content-Type: "application/x-www-form-urlencoded"
E, [2018-07-12T10:30:40.453562 #25340] ERROR -- : SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:852:in `start'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:1398:in `request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response/logger.rb:26:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/request/url_encoded.rb:15:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/request/multipart.rb:15:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/faraday/request.rb:25:in `request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/faraday/request.rb:10:in `post'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/api/endpoints/rtm.rb:37:in `rtm_start'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:110:in `build_socket'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:50:in `start!'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:37:in `start!'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:29:in `block (2 levels) in run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:69:in `handle_exceptions'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:27:in `block in run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:26:in `loop'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:26:in `run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/bot.rb:6:in `run'
F:/Projects/ruby/slack-bot-on-rails/config.ru:8:in `block (2 levels) in <main>'
I, [2018-07-12T10:30:41.454893 #25340]  INFO -- request: POST https://slack.com/api/rtm.start
D, [2018-07-12T10:30:41.456877 #25340] DEBUG -- request: Accept: "application/json; charset=utf-8"
User-Agent: "Slack Ruby Client/0.11.1"
Content-Type: "application/x-www-form-urlencoded"
E, [2018-07-12T10:30:41.513726 #25340] ERROR -- : SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:852:in `start'
F:/Ruby/ruby/lib/ruby/2.3.0/net/http.rb:1398:in `request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response/logger.rb:26:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/request/url_encoded.rb:15:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/request/multipart.rb:15:in `call'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/faraday/request.rb:25:in `request'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/faraday/request.rb:10:in `post'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/api/endpoints/rtm.rb:37:in `rtm_start'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:110:in `build_socket'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:50:in `start!'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:37:in `start!'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:29:in `block (2 levels) in run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:69:in `handle_exceptions'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:27:in `block in run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:26:in `loop'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/server.rb:26:in `run'
F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/bot.rb:6:in `run'
F:/Projects/ruby/slack-bot-on-rails/config.ru:8:in `block (2 levels) in <main>'
```

**Comment by zekedran** [comment]
And a bunch of warnings

```
Warning:Get available generators script executes with errors:
Warning:Please update your processor interface:
Warning:https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
Warning: (called from configure_env at F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/sprockets-coffee-react-4.0.1/lib/sprockets/coffee-react/engine.rb:18)
Warning:Please update your processor interface:
Warning:https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
Warning: (called from configure_env at F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/sprockets-coffee-react-4.0.1/lib/sprockets/coffee-react/engine.rb:19)
Warning:Please register a mime type using `register_mime_type` then
Warning:use `register_compressor` or `register_transformer`.
Warning:https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
Warning: (called from configure_env at F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/sprockets-coffee-react-4.0.1/lib/sprockets/coffee-react/engine.rb:20)
Warning:Please register a mime type using `register_mime_type` then
Warning:use `register_compressor` or `register_transformer`.
Warning:https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
Warning: (called from configure_env at F:/Ruby/ruby/lib/ruby/gems/2.3.0/gems/sprockets-coffee-react-4.0.1/lib/sprockets/coffee-react/engine.rb:21)
```

**Comment by zekedran** [comment]
Yup, https://slack.com/api works just fine. Time is synced as well and I do not have certificate issues elsewhere. I tried celluloid-io first and so I also tried faye-websocket, but it looks like the problem is in the cert rather than in one of those libs.

**Comment by zekedran** [comment]
Any way to fix the certificate error?

**Comment by dblock** [comment]
What OS are you on? Seems like a common problem, try http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by zekedran** [comment]
I'm on Windows 10, and notice this is not that pesky `state=sslv3 read server certificate b` SSLv3 error, seems it's due to something else :/

**Comment by dblock** [comment]
I don't have much to add to the SSL problem, but it's not an issue with this gem, but with Ruby + SSL in general in your installation. You should be able to google/fix that one.
